version: '3.1'

services:

  mongodb:
    image: mongo
    env_file:
      - ./envs/mongo.env
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    ports:
      - 80:80
    env_file:
      - ./envs/backend.env
    depends_on:
      - mongodb
      
  frontend:
    build: ./frontend
    ports:
      - 3030:3000
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
      - backend
    

    

volumes:
  data:
